apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
    app.kubernetes.io/name: app-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: app-service
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.appService.service.port }}
