apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-v1
spec:
  replicas: {{ .Values.appService.replicaCount }}
  selector:
    matchLabels:
      app: app-service
      version: v1-stable
  template:
    metadata:
      labels:
        app: app-service
        version: v1-stable
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: app-service
        image: "{{ .Values.appService.image }}"
        ports:
        - containerPort: {{ .Values.appService.service.port }}
        env:
        - name: MODEL_SERVICE_URL
          value: {{ .Values.appService.modelServiceUrl | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
