{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    # Use the variable we just created (Excellent criteria)
    istio: {{ .Values.istio.gateway.name }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - {{ .Values.hostname | quote }}
      {{- if .Values.prereleaseHostname }}
      - {{ .Values.prereleaseHostname | quote }}
      {{- end }}
      {{- if .Values.metricsHostname }}
      - {{ .Values.metricsHostname | quote }}
      {{- end }}
{{- end }}
