apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
      volumes:
      - name: shared-data-volume
        hostPath:
          path: {{ .Values.sharedVolume.hostPath }}
      containers:
      - name: model-service
        image: "{{ .Values.modelService.image }}"
        ports:
        - containerPort: {{ .Values.modelService.service.port }}
        volumeMounts:
        - name: shared-data-volume
          mountPath: {{ .Values.sharedVolume.mountPath }}