apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
      volumes:
      - name: shared-data-volume
        hostPath:
          path: {{ .Values.sharedVolume.hostPath }}
      containers:
      - name: model-service
        image: "{{ .Values.modelService.image }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: {{ .Values.modelService.service.port }}
          protocol: TCP
        env:
        - name: MODEL_FILE
          value: "output/model.joblib"
        volumeMounts:
        - name: shared-data-volume
          mountPath: {{ .Values.sharedVolume.mountPath }}
