apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-v2
  labels:
    app: model-service
    version: v2
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: model-service
      version: v2
  template:
    metadata:
      labels:
        app: model-service
        version: v2
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
      volumes:
        - name: shared-data-volume
          hostPath:
            path: {{ .Values.sharedVolume.hostPath }}
      containers:
        - name: model-service
          image: "{{ .Values.modelService.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: MODEL_FILE
              value: "output/model.joblib"
          ports:
            - name: http
              containerPort: {{ .Values.modelService.service.port }}
              protocol: TCP
          volumeMounts:
            - name: shared-data-volume
              mountPath: {{ .Values.sharedVolume.mountPath }}
