apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-v1
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: model-service
      version: v1-stable
  template:
    metadata:
      labels:
        app: model-service
        version: v1-stable
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      volumes:
        - name: shared-data-volume
          hostPath:
            path: {{ .Values.sharedVolume.hostPath }}

      containers:
      - name: model-service
        image: "{{ .Values.modelService.image }}"
        ports:
        - containerPort: {{ .Values.modelService.service.port }}
        env:
        - name: MODEL_FILE
          value: "{{ .Values.modelService.modelFile }}"
        - name: MODEL_URL
          value: "https://github.com/doda25-team19/model-service/releases/download/v{{ .Values.modelService.modelVersion }}/model.joblib"
        - name: PREPROCESSOR_URL
          value: "https://github.com/doda25-team19/model-service/releases/download/v{{ .Values.modelService.modelVersion }}/preprocessor.joblib"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
