{{- if and .Values.istio.rateLimiting.enabled (eq .Values.istio.rateLimiting.mode "global") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.istio.rateLimiting.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: grpc
      port: {{ .Values.istio.rateLimiting.service.port }}
      targetPort: {{ .Values.istio.rateLimiting.service.port }}
  selector:
    app: {{ .Release.Name }}-ratelimit
{{- end }}
